version: '3.8'
services:
  postgres:
    image: postgres:18-alpine
    container_name: nicandb
    environment:
      POSTGRES_DB: nicandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_/var/lib/postgresql/data

volumes:
  postgres_
